### ISSUE TITLE
Add US States, US Counties and US Zip Codes

### ISSUE THREAD

**Issue by chadladensack** [remithomas/rt-extends#1]
The current data country and language support is great.  By adding data store support for US states, US counties and US zip codes a lot could be gained for a plethora of projects including (but not limited to) eCommerce, advertising and government related projects.

I'll do some digging around to locate a reliable external source to populate the county and zip code data.  I'm aware of StrikeIron but I was looking for something more readily available and open source.

**Comment by remithomas** [comment]
This is a good idea ! I will work on very soon ! 
If you have more ides like this, don't hesitate to contact me or work on !
Cheers
